name: PR Comment

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          comment: |
            Hello BBZW ! :wave:
